#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Check code formatting with eslint and prettier"
echo '\e[1;44m'"\nValidating code patterns with eslint"'\e[0m'
yarn lint 

echo '\e[1;45m'"\nValidating code formatting with prettier"'\e[0m'
yarn prettier